//server
export const LOAD_MAIN_FOOD_CATALOG = "LOAD_MAIN_FOOD_CATALOG";
export const LOAD_USER_FOOD_CATALOG = "LOAD_USER_FOOD_CATALOG";
export const LOAD_USER_DIARY = "LOAD_USER_DIARY";
//interface
export const FOOD_SERCH = "FOOD_SERCH";
export const ADD_USER_DISH = "ADD_USER_DISH";
export const EDIT_USER_DISH = "EDIT_USER_DISH";
export const DELETE_USER_DISH = "DELETE_USER_DISH";
